

SERVE_PATH = 'docs/'
RAW = 'articles/'

CNAME = SERVE_PATH+"CNAME"

METADATA_FILE_NAME = 'metadata.json'

TEXT_FILE_NAME = 'text.md'

ENTRIES_NAME="entries/"
ENTRIES = SERVE_PATH+ENTRIES_NAME

ASSETS_FOLDER = "assets/"

ASSETS_ENTRIES_FOLDER = ENTRIES + ASSETS_FOLDER

TEMPLATE_PATH = 'templates/'
ELEMENTS_PATH = TEMPLATE_PATH + "elements/"
FOOTER_PATH = ELEMENTS_PATH + "footer.html"

HEADER_PATH = ELEMENTS_PATH + "header.html"

BLOG_TEMPLATE =  TEMPLATE_PATH + ENTRIES_NAME+ 'blogTemplate.html'

LINK_TEMPLATE =  TEMPLATE_PATH + 'linkTemplate.html'
INDEX_TEMPLATE =  TEMPLATE_PATH + 'indexTemplate.html'

PREFETCH_TEMPLATE =  TEMPLATE_PATH + 'prefetchTemplate.html'

STYLES = "styles/"
ASSETS_FOLDER = "assets/"